import {z} from 'zod'

import {BasicVmConfigSchema, VmConfigSchema} from './schemas'
import type {
  AcmeInfo,
  AppInfo,
  AppMetadata,
  AttestationBundle,
  CTResult,
  DataObject,
  GatewayMetadata,
  KmsMetadata,
  ObjectRelationship,
  QuoteData,
  VerificationFailure,
  VerifyQuoteResult,
} from './types'
import type {DataObjectCollector} from './utils/dataObjectCollector'
import {decodeQuote} from './utils/dcap-qvl'
import {verifyTeeQuote} from './verification/hardwareVerification'
import {
  type DstackVerificationResponse,
  verifyDstackEvidence,
} from './verification/osVerification'

/**
 * Abstract base class for TEE (Trusted Execution Environment) application verification.
 *
 * This class defines the interface for verifying different aspects of a TEE application:
 * hardware attestation, operating system integrity, and source code authenticity.
 * It also provides DataObject generation capabilities for visualization.
 */
export abstract class Verifier {
  protected metadata: KmsMetadata | GatewayMetadata | AppMetadata
  protected relationships: ObjectRelationship[] = []
  protected objectIdPrefix: string
  protected collector: DataObjectCollector
  private evidencePromise?: Promise<{quoteData: QuoteData; appInfo: AppInfo}>
  private cvmVerificationPromise?: Promise<DstackVerificationResponse | null>

  protected getVerificationEvidence(): Promise<{
    quoteData: QuoteData
    appInfo: AppInfo
  }> {
    this.evidencePromise ??= Promise.all([
      this.getQuote(),
      this.getAppInfo(),
    ]).then(([quoteData, appInfo]) => ({
      quoteData,
      appInfo: quoteData.vm_config
        ? {
            ...appInfo,
            vm_config: z
              .union([VmConfigSchema, BasicVmConfigSchema])
              .parse(JSON.parse(quoteData.vm_config)),
          }
        : appInfo,
    }))
    return this.evidencePromise
  }

  protected getCvmVerification(): Promise<DstackVerificationResponse | null> {
    this.cvmVerificationPromise ??= this.verifyCvmEvidence()
    return this.cvmVerificationPromise
  }

  protected async getHardwareEvidence(): Promise<{
    quoteData: QuoteData
    verificationResult: VerifyQuoteResult
  }> {
    const {quoteData} = await this.getVerificationEvidence()
    const result = await this.getCvmVerification()
    if (!result) {
      return {quoteData, verificationResult: await verifyTeeQuote(quoteData)}
    }
    // Rust verifies quote, event log and OS binding as one operation.
    // Disabling the OS report must not downgrade a failed modern attestation.
    if (
      !result.is_valid ||
      !result.details.quote_verified ||
      !result.details.tcb_status
    ) {
      throw new Error(
        result.reason || 'dstack-verifier quote verification failed',
      )
    }
    // Decode the same verified quote for display-only TD report fields.
    const decoded = await decodeQuote(quoteData.quote, {hex: true})
    return {
      quoteData,
      verificationResult: {
        status: result.details.tcb_status,
        advisory_ids: result.details.advisory_ids,
        report: decoded.report,
      },
    }
  }

  private async verifyCvmEvidence(): Promise<DstackVerificationResponse | null> {
    const {quoteData, appInfo} = await this.getVerificationEvidence()
    const vmConfig = quoteData.vm_config
      ? JSON.parse(quoteData.vm_config)
      : appInfo.vm_config
    if (!vmConfig || typeof vmConfig !== 'object' || Array.isArray(vmConfig)) {
      throw new Error('Invalid VM configuration in attestation evidence')
    }
    if (
      !('spec_version' in vmConfig) &&
      !('tdx_attestation_variant' in vmConfig)
    ) {
      return null
    }
    const result = await verifyDstackEvidence({
      quote: quoteData.quote,
      event_log: JSON.stringify(quoteData.eventlog),
      vm_config: quoteData.vm_config || JSON.stringify(appInfo.vm_config),
    })
    if (result.is_valid && result.details.app_info) {
      const verified = result.details.app_info
      const normalize = (value: string) =>
        value.replace(/^0x/, '').toLowerCase()
      if (
        normalize(verified.app_id) !== normalize(appInfo.app_id) ||
        (appInfo.instance_id &&
          normalize(verified.instance_id) !== normalize(appInfo.instance_id)) ||
        (quoteData.instance_id &&
          normalize(verified.instance_id) !== normalize(quoteData.instance_id))
      ) {
        throw new Error(
          'dstack-verifier evidence does not match the requested app instance',
        )
      }
    }
    return result
  }

  /**
   * Constructor for the base Verifier class.
   *
   * @param metadata - Structured metadata for verification
   * @param objectIdPrefix - Prefix for DataObject IDs generated by this verifier
   * @param collector - DataObjectCollector instance for this verification
   */
  constructor(
    metadata: KmsMetadata | GatewayMetadata | AppMetadata,
    objectIdPrefix: string,
    collector: DataObjectCollector,
  ) {
    this.metadata = metadata
    this.objectIdPrefix = objectIdPrefix
    this.collector = collector
  }

  /**
   * Add relationships that will be applied when DataObjects are created.
   *
   * @param relationships - Array of relationship definitions
   */
  public addRelationships(relationships: ObjectRelationship[]): void {
    this.relationships.push(...relationships)
    this.collector.addRelationships(relationships)
  }

  /**
   * Create a DataObject and add it to the collector.
   *
   * @param dataObject - The DataObject to create
   */
  protected createDataObject(dataObject: DataObject): void {
    this.collector.createOrUpdateObject(dataObject)
  }

  /**
   * Generate a unique object ID with the verifier's prefix.
   *
   * @param suffix - Suffix to append to the prefix
   * @returns Generated object ID
   */
  protected generateObjectId(suffix: string): string {
    return `${this.objectIdPrefix}-${suffix}`
  }

  /**
   * Retrieves the cryptographic quote and event log from the TDX environment.
   *
   * @returns Promise resolving to the quote and event log data
   */
  protected abstract getQuote(): Promise<QuoteData>

  /**
   * Retrieves both Intel TDX and NVIDIA GPU attestation data.
   *
   * @returns Promise resolving to the complete attestation bundle or null if unavailable
   */
  protected abstract getAttestation(): Promise<AttestationBundle | null>

  /**
   * Retrieves application information from the DStack Guest Agent.
   *
   * This data is typically acquired from the local guest agent endpoint:
   * http://${GUEST_AGENT_ADDR}/prpc/Info
   *
   * @returns Promise resolving to the application information
   */
  protected abstract getAppInfo(): Promise<AppInfo>

  /**
   * Verifies the hardware attestation signatures (Intel TDX and NVIDIA GPU).
   *
   * @returns Promise resolving to verification result with failures array
   */
  public abstract verifyHardware(): Promise<{
    isValid: boolean
    failures: VerificationFailure[]
  }>

  /**
   * Verifies the integrity of the operating system image.
   *
   * @returns Promise resolving to verification result with failures array
   */
  public abstract verifyOperatingSystem(): Promise<{
    isValid: boolean
    failures: VerificationFailure[]
  }>

  /**
   * Verifies the authenticity of the source code through compose hash validation.
   *
   * @returns Promise resolving to verification result with failures array
   */
  public abstract verifySourceCode(): Promise<{
    isValid: boolean
    failures: VerificationFailure[]
  }>

  /**
   * Get the verifier's metadata.
   *
   * @returns The metadata object
   */
  public getVerifierMetadata(): KmsMetadata | GatewayMetadata | AppMetadata {
    return this.metadata
  }

  /**
   * Update the verifier's metadata.
   *
   * @param newMetadata - New metadata to merge
   */
  public updateMetadata(
    newMetadata: Partial<KmsMetadata | GatewayMetadata | AppMetadata>,
  ): void {
    this.metadata = {...this.metadata, ...newMetadata}
  }
}

/**
 * Abstract class for verifying TEE-controlled domain ownership and certificate management.
 *
 * This class provides methods to verify that a domain is completely controlled by a TEE
 * through ACME certificate management, DNS records, and Certificate Transparency logs.
 */
export abstract class OwnDomain {
  /**
   * Retrieves ACME account information with TEE-controlled cryptographic keys.
   *
   * @returns Promise resolving to ACME account details and key information
   */
  public abstract getAcmeInfo(): Promise<AcmeInfo>

  /**
   * Verifies that the public key is controlled by the TEE by checking quote report_data.
   *
   * This ensures the private key corresponding to the public key is generated and
   * stored within the TEE and cannot be extracted.
   *
   * @returns Promise resolving to verification result
   */
  public abstract verifyTeeControlledKey(): Promise<{
    isValid: boolean
    error?: string
  }>

  /**
   * Verifies that the TLS certificate matches the TEE-controlled public key.
   *
   * @returns Promise resolving to verification result
   */
  public abstract verifyCertificateKey(): Promise<{
    isValid: boolean
    error?: string
  }>

  /**
   * Verifies domain control through DNS CAA (Certificate Authority Authorization) records.
   *
   * This ensures the domain can only issue certificates through the TEE-controlled
   * Let's Encrypt account.
   *
   * @returns Promise resolving to verification result
   */
  public abstract verifyDnsCAA(): Promise<{
    isValid: boolean
    error?: string
  }>

  /**
   * Verifies complete TEE control over the domain through Certificate Transparency logs.
   *
   * This method analyzes historical certificate issuance to ensure the domain has
   * always been controlled by the TEE and no unauthorized certificates exist.
   *
   * @returns Promise resolving to detailed CT log verification results
   */
  public abstract verifyCTLog(): Promise<CTResult>
}
