import type {
  AcmeInfo,
  AppInfo,
  AttestationBundle,
  CTResult,
  DataObject,
  ObjectRelationship,
  QuoteData,
  VerifierMetadata,
} from './types'
import {
  addDataObjectRelationships,
  createDataObject,
} from './utils/dataObjectCollector'

/**
 * Abstract base class for TEE (Trusted Execution Environment) application verification.
 *
 * This class defines the interface for verifying different aspects of a TEE application:
 * hardware attestation, operating system integrity, and source code authenticity.
 * It also provides DataObject generation capabilities for visualization.
 */
export abstract class Verifier {
  protected metadata: VerifierMetadata
  protected relationships: ObjectRelationship[] = []
  protected objectIdPrefix: string

  /**
   * Constructor for the base Verifier class.
   *
   * @param metadata - Metadata containing OS version and other configuration
   * @param objectIdPrefix - Prefix for DataObject IDs generated by this verifier
   */
  constructor(metadata: VerifierMetadata = {}, objectIdPrefix = 'verifier') {
    this.metadata = metadata
    this.objectIdPrefix = objectIdPrefix
  }

  /**
   * Add relationships that will be applied when DataObjects are created.
   *
   * @param relationships - Array of relationship definitions
   */
  public addRelationships(relationships: ObjectRelationship[]): void {
    this.relationships.push(...relationships)
    addDataObjectRelationships(relationships)
  }

  /**
   * Create a DataObject and add it to the global collector.
   *
   * @param dataObject - The DataObject to create
   */
  protected createDataObject(dataObject: DataObject): void {
    createDataObject(dataObject)
  }

  /**
   * Generate a unique object ID with the verifier's prefix.
   *
   * @param suffix - Suffix to append to the prefix
   * @returns Generated object ID
   */
  protected generateObjectId(suffix: string): string {
    return `${this.objectIdPrefix}-${suffix}`
  }

  /**
   * Retrieves the cryptographic quote and event log from the TDX environment.
   *
   * @returns Promise resolving to the quote and event log data
   */
  protected abstract getQuote(): Promise<QuoteData>

  /**
   * Retrieves both Intel TDX and NVIDIA GPU attestation data.
   *
   * @returns Promise resolving to the complete attestation bundle or null if unavailable
   */
  protected abstract getAttestation(): Promise<AttestationBundle | null>

  /**
   * Retrieves application information from the DStack Guest Agent.
   *
   * This data is typically acquired from the local guest agent endpoint:
   * http://${GUEST_AGENT_ADDR}/prpc/Info
   *
   * @returns Promise resolving to the application information
   */
  protected abstract getAppInfo(): Promise<AppInfo>

  /**
   * Verifies the hardware attestation signatures (Intel TDX and NVIDIA GPU).
   *
   * @returns Promise resolving to true if hardware attestation is valid
   */
  public abstract verifyHardware(): Promise<boolean>

  /**
   * Verifies the integrity of the operating system image.
   *
   * @returns Promise resolving to true if OS integrity is verified
   */
  public abstract verifyOperatingSystem(): Promise<boolean>

  /**
   * Verifies the authenticity of the source code through compose hash validation.
   *
   * @returns Promise resolving to true if source code is verified
   */
  public abstract verifySourceCode(): Promise<boolean>

  /**
   * Get the verifier's metadata.
   *
   * @returns The metadata object
   */
  public getVerifierMetadata(): VerifierMetadata {
    return this.metadata
  }

  /**
   * Update the verifier's metadata.
   *
   * @param newMetadata - New metadata to merge
   */
  public updateMetadata(newMetadata: Partial<VerifierMetadata>): void {
    this.metadata = {...this.metadata, ...newMetadata}
  }
}

/**
 * Abstract class for verifying TEE-controlled domain ownership and certificate management.
 *
 * This class provides methods to verify that a domain is completely controlled by a TEE
 * through ACME certificate management, DNS records, and Certificate Transparency logs.
 */
export abstract class OwnDomain {
  /**
   * Retrieves ACME account information with TEE-controlled cryptographic keys.
   *
   * @returns Promise resolving to ACME account details and key information
   */
  public abstract getAcmeInfo(): Promise<AcmeInfo>

  /**
   * Verifies that the public key is controlled by the TEE by checking quote report_data.
   *
   * This ensures the private key corresponding to the public key is generated and
   * stored within the TEE and cannot be extracted.
   *
   * @returns Promise resolving to true if the key is TEE-controlled
   */
  public abstract verifyTeeControlledKey(): Promise<boolean>

  /**
   * Verifies that the TLS certificate matches the TEE-controlled public key.
   *
   * @returns Promise resolving to true if certificate key matches TEE key
   */
  public abstract verifyCertificateKey(): Promise<boolean>

  /**
   * Verifies domain control through DNS CAA (Certificate Authority Authorization) records.
   *
   * This ensures the domain can only issue certificates through the TEE-controlled
   * Let's Encrypt account.
   *
   * @returns Promise resolving to true if DNS CAA records are properly configured
   */
  public abstract verifyDnsCAA(): Promise<boolean>

  /**
   * Verifies complete TEE control over the domain through Certificate Transparency logs.
   *
   * This method analyzes historical certificate issuance to ensure the domain has
   * always been controlled by the TEE and no unauthorized certificates exist.
   *
   * @returns Promise resolving to detailed CT log verification results
   */
  public abstract verifyCTLog(): Promise<CTResult>
}
